import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const exmaples = trpc.useQuery(["example.getAll"]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta
          name="description"
          content="Generated by create-t3-app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>

      <div
        className="pt-6 text-2xl text-blue-500 flex justify-center items-center w-full"
      >
        {exmaples.data ?
          <p>{exmaples.data.map(i => <span key={i.id}>{i.id}</span>)}</p> : <p>Loading..</p>}
      </div>
    </>
  );
};

export default Home;
